### ISSUE TITLE
Looking for mysql socket in unix path on windows

### ISSUE THREAD

**Issue by kde99** [EVEIPH/EVE-SDE-Database-Builder#1]
So I tried to import the data into a mysql database:

```
An Unhandled Exception has occured and the program will now close.
Copy the data below and send to developer.

Source: Microsoft.VisualBasic
Message: Can't get stat of '/var/lib/mysql/eve_esd/agtAgents.csv' (Errcode: 2 "No such file or directory")
Raw Error Text: MySql.Data.MySqlClient.MySqlException (0x80004005): Can't get stat of '/var/lib/mysql/eve_esd/agtAgents.csv' (Errcode: 2 "No such file or directory")
   at Microsoft.VisualBasic.CompilerServices.Symbols.Container.InvokeMethod(Method TargetProcedure, Object[] Arguments, Boolean[] CopyBack, BindingFlags Flags)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.CallMethod(Container BaseReference, String MethodName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack, BindingFlags InvocationFlags, Boolean ReportErrors, ResolutionFailure& Failure)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.ObjectLateCall(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack, Boolean IgnoreReturn)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.LateCall(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack, Boolean IgnoreReturn)
   at EVE_SDE_Database_Builder.frmMain.BuildEVEDatabase(Object UpdateDatabase, DatabaseType DatabaseType)
   at EVE_SDE_Database_Builder.frmMain.btnBuildDatabase_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

As you can see it tries to access the mysql socket. Well since it's a windows there is so such thing as /var/lib/mysql (a unix socket).

**Comment by Zifrian** [comment]
I get the folder name for mysql from the query, which is unique for each computer I guess. Is there another way to set it? This seems to be a sticking point for most issues. MySQL can't import csv files as bulk load from another folder, it needs to be the one set by the database. Any ideas?

**Comment by kde99** [comment]
@Zifrian  well if I create an sqlite one first then I can import that to mysql that works but it takes a longer time.

**Comment by Zifrian** [comment]
Wait, you create an sqlite version and then run mysql and it works? If so, that's really weird but something I should be able to fix.

**Comment by kde99** [comment]
@Zifrian well I can't import it into mysql from this app but I can import it to sqlite. then I can import the sqlite tables into mysql using an other app. But creating an sqlite then importing that takes quite a long time for nothing.

**Comment by Zifrian** [comment]
OK I put up a potential fix. I found a similar issue on stack overload and made the change suggested there. Update the program and let me know if it works.

**Comment by Zifrian** [comment]
Is this working now?
