### ISSUE TITLE
Getting 22P02: invalid input syntax for integer: "false"

### ISSUE THREAD

**Issue by oleksm** [EVEIPH/EVE-SDE-Database-Builder#10]
I am building latest snapshot for postgres and getting this error on final step (after all swimlanes are 100% ) I can see that some tables are populates with data and some (like invtypes) are not
-----------
An Unhandled Exception has occured and the program will now close.
Copy the data below and send to developer.

Source: Microsoft.VisualBasic
Message: 22P02: invalid input syntax for integer: "false"
Raw Error Text: Npgsql.PostgresException (0x80004005): 22P02: invalid input syntax for integer: "false"
   at Microsoft.VisualBasic.CompilerServices.Symbols.Container.InvokeMethod(Method TargetProcedure, Object[] Arguments, Boolean[] CopyBack, BindingFlags Flags)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.CallMethod(Container BaseReference, String MethodName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack, BindingFlags InvocationFlags, Boolean ReportErrors, ResolutionFailure& Failure)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.ObjectLateCall(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack, Boolean IgnoreReturn)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.LateCall(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack, Boolean IgnoreReturn)
   at EVE_SDE_Database_Builder.frmMain.BuildEVEDatabase(Object UpdateDatabase, DatabaseType DatabaseType)
   at EVE_SDE_Database_Builder.frmMain.btnBuildDatabase_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Please suggest if there some quick workaround.

**Comment by Zifrian** [comment]
Thanks for letting me know. Need to update a few things but I'll try and get it fixed soon.

**Comment by Zifrian** [comment]
OK put a fix up. Let me know if you still have issues after updating.
