### ISSUE TITLE
SQLite error when trying to load to MS SQL

### ISSUE THREAD

**Issue by ManaRose** [EVEIPH/EVE-SDE-Database-Builder#14]
I tried importing to a MS SQL DB and I consistently get the below error. The status bar says "Preparing Files..." when this happens. Import directory is D:\Eve Stuff\sde\sde. Let me know if I can provide any more info.

11/26/2022 8:03:18 PM, System.EntryPointNotFoundException: Unable to find an entry point named 'SI7fca2652f71267db' in DLL 'SQLite.Interop.dll'.
   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
   at System.Data.SQLite.SQLite3.StaticIsInitialized()
   at System.Data.SQLite.SQLiteLog.PrivateInitialize(String className)
   at System.Data.SQLite.SQLiteLog.Initialize(String className)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor()
   at EVE_SDE_Database_Builder.SQLiteDB..ctor(String DatabaseFileNameandPath, String DBPath, Boolean& Success)
   at EVE_SDE_Database_Builder.YAMLTranslations..ctor(String YAMLFilePath, Object& DatabaseRef, String DBPath)
   at EVE_SDE_Database_Builder.frmMain.BuildEVEDatabase(Object UpdateDatabase, DatabaseType DatabaseType)
   at EVE_SDE_Database_Builder.frmMain.btnBuildDatabase_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Zifrian** [comment]
Thanks for the note. I updated the libraries and fixed several bugs. Please try to do an update (or a reinstall) and see if that helps.

Note: I'm having issues with threading and memory usage so reduce the threads (file menu) if you get a memory error.

**Comment by ManaRose** [comment]
Thanks for the quick reply. I just pulled the update and tried again, and this time I got the following. I tried playing with the thread count too, and downloading the SDE through the program, neither changed the error received. 

Source: System.Data.SQLite
Message: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
Raw Error Text: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
   at System.Data.SQLite.SQLite3.StaticIsInitialized()
   at System.Data.SQLite.SQLiteLog.PrivateInitialize(String className)
   at System.Data.SQLite.SQLiteLog.Initialize(String className)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor()
   at EVE_SDE_Database_Builder.SQLiteDB..ctor(String DatabaseFileNameandPath, String DBPath, Boolean& Success)
   at EVE_SDE_Database_Builder.YAMLTranslations..ctor(String YAMLFilePath, Object& DatabaseRef, String DBPath)
   at EVE_SDE_Database_Builder.frmMain.BuildEVEDatabase(Object UpdateDatabase, DatabaseType DatabaseType)
   at EVE_SDE_Database_Builder.frmMain.btnBuildDatabase_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by NightSkySK** [comment]
The same for me:
```
Source: System.Data.SQLite
Message: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
Raw Error Text: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
   at System.Data.SQLite.SQLite3.StaticIsInitialized()
   at System.Data.SQLite.SQLiteLog.PrivateInitialize(String className)
   at System.Data.SQLite.SQLiteLog.Initialize(String className)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor()
   at EVE_SDE_Database_Builder.SQLiteDB..ctor(String DatabaseFileNameandPath, String DBPath, Boolean& Success)
   at EVE_SDE_Database_Builder.frmMain.btnBuildDatabase_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   ```
   Just after I hit Buid database button to SQLite or CSV with the same result.

**Comment by Zifrian** [comment]
Can you redownload the program and try again? I upgraded to 64 bit. Also, are you using a64bit OS?

**Comment by NightSkySK** [comment]
Yes, it's on 64bit system 
![image](https://user-images.githubusercontent.com/52137446/205645422-c1ee272f-2ba0-4d3b-a119-6e5025e37609.png)

And I get this error on version downloaded today, so it was after recent commits for 64 bit updgrade

**Comment by Zifrian** [comment]
OK, thank you for this info. I'm getting the error when I run it from my local folder (install version) but not in the dev environment. It seems to be something related to 32 bit and 64bit but still working on it. Sorry about this, but thanks for the notes!

**Comment by Zifrian** [comment]
OK, I've completed several updates and updated the...updater. You'll need to download the newest binaries to get the changes since the updater was a bit of a mess. The 64 bit libraries should work now and I've updated all libraries to the current versions. Additionally, this version requires .Net 4.8 for both the updater and the main program if you need to install it. Finally, I did get a blue box from Windows telling me not to run the program, but it was because it's unsigned, which is common. 

Let me know if you still encounter any issues and thanks for the notes for any problems!

**Comment by ManaRose** [comment]
Looks like it's working now. Thank you so much for taking the time to make and support this utility!
